// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrtonooardfukiqyewmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJydG9ub29hcmRmdWtpcXlld216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTQ1MjIsImV4cCI6MjA2Nzg5MDUyMn0.OHeVQxps4CbAODwwgmJe2zhuGIyFNM6q75uoOyKpWLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});